# This file describes a Fastly Compute package. To learn more visit:
# https://www.fastly.com/documentation/reference/compute/fastly-toml

authors = ["andrew+fastly@mealies.co.uk"]
cloned_from = "https://github.com/fastly/compute-starter-kit-go-default"
description = "Scrabble scorer tool running on Fastly Compute"
language = "go"
manifest_version = 3
name = "wasmScrabbleScorer"
service_id = "ikBJO4tdW65QwifIMpstdE"

[local_server]

[scripts]
  build = "go build -o bin/main.wasm ."
  env_vars = ["GOARCH=wasm", "GOOS=wasip1"]
  post_init = "go get github.com/fastly/compute-sdk-go@latest"
